services:
  - type: web
    name: coin-trend-alert
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true

    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_SECRET
        sync: false
